"""init db

Revision ID: e4a77afb0a8c
Revises: 
Create Date: 2022-06-11 13:34:10.987642

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e4a77afb0a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campania',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('campania_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campania_id'], ['campania.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('campania')
    # ### end Alembic commands ###
